#!/bin/sh
# This script sets up "anonymous" for Kali Linux.

echo ""
echo "______ ___________________________  ______________  _________
___  //_/__    |__  /____  _/__   |/  /_  __ \_  / / /_  ___/
__  ,<  __  /| |_  /  __  / __  /|_/ /_  / / /  / / /_____ \ 
_  /| | _  ___ |  /____/ /  _  /  / / / /_/ // /_/ / ____/ / 
/_/ |_| /_/  |_/_____/___/  /_/  /_/  \____/ \____/  /____/ "
echo ""
echo "ANONYMOUS TOOL"
echo ""
echo "[*] Actualizando paquetes ..."
echo ""
apt update
echo ""
# Instalación de Tor y Macchanger
read -p "Tiene TOR instalado? [Y/n] (N si no está seguro)" tor
case $tor in
	[Nn]* ) apt install tor -y; break;;
	[Yy]* ) break;;
       	* ) echo "Input incorrecto!"; break;;
esac;
read -p "Tiene Macchanger instalado? [Y/n] (N si no está seguro)" tor
case $tor in
	[Nn]* ) apt install macchanger -y; break;;
	[Yy]* ) break;;
        * ) echo "Input incorrecto!"; break;;
esac;
